version: '3.8'
services:
    node:
        container_name: node
        image: node:14.17.3
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: /bin/bash -c "npm install -g npm@6.14.13 --registry https://registry.npm.taobao.org && npm install --registry https://registry.npm.taobao.org && npm run serve:dev"
        ports:
            - '3000:3000'
            - '8080:8080'
        networks:
            paradise-admin-net:
        restart: always

    nginx:
        container_name: nginx
        image: nginx:1.21.1
        
        volumes:
            - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8001:80'
        networks:
            paradise-admin-net:
        restart: always
        depends_on:
            - node

networks:
    paradise-admin-net:
