version: '3.8'
services:
    node:
        container_name: node
        image: paradise-admin-node:1.0.0
        command: /bin/bash -c "npm install -g npm@6.14.13 --registry https://registry.npm.taobao.org && npm install --production --registry https://registry.npm.taobao.org && npm run serve:server"
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        networks:
            paradise-admin-net:
        restart: always
        depends_on:
            - mysql

    nginx:
        container_name: nginx
        image: paradise-admin-nginx:1.0.0
        ports:
            - '${NGINX_PORT}:443'
        networks:
            paradise-admin-net:
        restart: always
        depends_on:
            - node
    mysql:
        container_name: mysql
        image: mysql:5.7
        command:
            [
                '--character-set-server=utf8',
                '--collation-server=utf8_general_ci',
                '--default-time-zone=+8:00',
            ]
        volumes:
            - /home/mysql/data:/var/lib/mysql
        ports:
            - ${DB_PORT}:${DB_PORT}
        restart: always
        networks:
            paradise-admin-net:
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DBNAME}
networks:
    paradise-admin-net:
