version: '3.8'
services:
    node:
        container_name: node
        image: node:14.17.3
        working_dir: /usr/src/app
        volumes:
            - server:/usr/src/app/server
            - .env:/usr/src/app/.env
        command: /bin/bash -c "npm install -g npm@6.14.13 --registry https://registry.npm.taobao.org && npm install --registry https://registry.npm.taobao.org && npm run serve"

        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${VUE_APP_PORT}:${SERVER_PORT}
        networks:
            paradise-admin-net:
        restart: always
        depends_on:
            - mysql

    nginx:
        container_name: nginx
        image: nginx:1.21.1

        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./apidocs:/usr/share/nginx/html/apidoc
        ports:
            - '${NGINX_PORT}:80'
        networks:
            paradise-admin-net:
        restart: always
        depends_on:
            - node
    mysql:
        container_name: mysql
        image: mysql:5.7
        command:
            [
                '--character-set-server=utf8',
                '--collation-server=utf8_general_ci',
                '--default-time-zone=+8:00',
            ]
        volumes:
            # - ./db/data:/var/lib/mysql
            - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        ports:
            - ${DB_PORT}:${DB_PORT}
        restart: always
        networks:
            paradise-admin-net:
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DBNAME}
networks:
    paradise-admin-net:
