const menuTree = [
	{
		id: 1,
		name: '首页',
		icon: 'el-icon-s-home',
		path: '/home',
		parent_id: 0,
		disabled: true,
	},
	{
		id: 2,
		parent_id: 0,
		name: '幽冥界',
		icon: 'iconfont icon-kulou',
		path: '/hell',
		children: [
			{
				name: '阎罗殿',
				path: '/hell',
				id: 10,
				parent_id: 2,
			},
			{
				name: '鬼门关',
				path: '/hell/danger-spot',
				id: 11,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '黄泉路',
				path: '/hell',
				id: 12,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '奈何桥',
				path: '/hell',
				id: 13,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '孟婆亭',
				path: '/hell',
				id: 14,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '三生石',
				path: '/hell',
				id: 15,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '望乡台',
				path: '/hell/township',
				id: 16,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '忘川河',
				path: '/hell',
				id: 17,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '六道轮回',
				path: '/hell/reincarnation',
				id: 18,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '九幽地府',
				path: '/hell',
				id: 19,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '枉死城',
				path: '/hell',
				id: 20,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '生死簿',
				path: '/hell/obituary',
				id: 21,
				parent_id: 2,
				permissions: [],
			},
			{
				name: '十八层地狱',
				path: '/hell',
				isGroup: true,
				id: 22,
				parent_id: 2,
				permissions: [],
				children: [
					{
						name: '第一层',
						path: '/hell',
						id: 30,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_ONE_C' },
							{ state: false, v: 'HELL_ONE_U' },
							{ state: false, v: 'HELL_ONE_D' },
						],
					},
					{
						name: '第2层',
						path: '/hell',
						id: 31,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_TWO_C' },
							{ state: false, v: 'HELL_TWO_U' },
							{ state: false, v: 'HELL_TWO_D' },
						],
					},
					{
						name: '第3层',
						path: '/hell',
						id: 32,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_THREE_C' },
							{ state: false, v: 'HELL_THREE_U' },
							{ state: false, v: 'HELL_THREE_D' },
						],
					},
					{
						name: '第4层',
						path: '/hell',
						id: 33,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_FOUR_C' },
							{ state: false, v: 'HELL_FOUR_U' },
							{ state: false, v: 'HELL_FOUR_D' },
						],
					},
					{
						name: '第5层',
						path: '/hell',
						id: 34,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_FIVES_C' },
							{ state: false, v: 'HELL_FIVES_U' },
							{ state: false, v: 'HELL_FIVES_D' },
						],
					},
					{
						name: '第6层',
						path: '/hell',
						id: 35,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_SIXTY_C' },
							{ state: false, v: 'HELL_SIXTY_U' },
							{ state: false, v: 'HELL_SIXTY_D' },
						],
					},
					{
						name: '第7层',
						path: '/hell',
						id: 36,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_SEVEN_C' },
							{ state: false, v: 'HELL_SEVEN_U' },
							{ state: false, v: 'HELL_SEVEN_D' },
						],
					},
					{
						name: '第8层',
						path: '/hell',
						id: 37,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_EIGHT_C' },
							{ state: false, v: 'HELL_EIGHT_U' },
							{ state: false, v: 'HELL_EIGHT_D' },
						],
					},
					{
						name: '第9层',
						path: '/hell',
						id: 38,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_NINE_C' },
							{ state: false, v: 'HELL_NINE_U' },
							{ state: false, v: 'HELL_NINE_D' },
						],
					},
					{
						name: '第10层',
						path: '/hell',
						id: 39,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_TEN_C' },
							{ state: false, v: 'HELL_TEN_U' },
							{ state: false, v: 'HELL_TEN_D' },
						],
					},
					{
						name: '第11层',
						path: '/hell',
						id: 40,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_ELEVEN_C' },
							{ state: false, v: 'HELL_ELEVEN_U' },
							{ state: false, v: 'HELL_ELEVEN_D' },
						],
					},
					{
						name: '第12层',
						path: '/hell',
						id: 41,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_TWELVE_C' },
							{ state: false, v: 'HELL_TWELVE_U' },
							{ state: false, v: 'HELL_TWELVE_D' },
						],
					},
					{
						name: '第13层',
						path: '/hell',
						id: 42,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_THIRTEEN_C' },
							{ state: false, v: 'HELL_THIRTEEN_U' },
							{ state: false, v: 'HELL_THIRTEEN_D' },
						],
					},
					{
						name: '第14层',
						path: '/hell',
						id: 43,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_FOURTEEN_C' },
							{ state: false, v: 'HELL_FOURTEEN_U' },
							{ state: false, v: 'HELL_FOURTEEN_D' },
						],
					},
					{
						name: '第15层',
						path: '/hell',
						id: 44,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_FIFTEEN_C' },
							{ state: false, v: 'HELL_FIFTEEN_U' },
							{ state: false, v: 'HELL_FIFTEEN_D' },
						],
					},
					{
						name: '第16层',
						path: '/hell',
						id: 45,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_SIXTEEN_C' },
							{ state: false, v: 'HELL_SIXTEEN_U' },
							{ state: false, v: 'HELL_SIXTEEN_D' },
						],
					},
					{
						name: '第17层',
						path: '/hell',
						id: 46,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_SEVENTEEN_C' },
							{ state: false, v: 'HELL_SEVENTEEN_U' },
							{ state: false, v: 'HELL_SEVENTEEN_D' },
						],
					},
					{
						name: '第18层',
						path: '/hell',
						id: 47,
						parent_id: 22,
						permissions: [
							{ state: false, v: 'HELL_EIGHTEEN_C' },
							{ state: false, v: 'HELL_EIGHTEEN_U' },
							{ state: false, v: 'HELL_EIGHTEEN_D' },
						],
					},
				],
			},
		],
	},
	{
		id: 3,
		parent_id: 0,
		name: '人界',
		icon: 'iconfont icon-ren',
		path: '/world',
		permissions: [],
		children: [
			{
				name: '统计',
				path: '/world',
				id: 23,
				parent_id: 3,
				permissions: [],
			},
			{
				name: '东胜神州',
				path: '/world/territory/east',
				id: 24,
				parent_id: 3,
				permissions: [],
			},
			{
				name: '南澹部洲',
				path: '/world/territory/south',
				id: 25,
				parent_id: 3,
				permissions: [],
			},
			{
				name: '西牛贺洲',
				path: '/world/territory/west',
				id: 26,
				parent_id: 3,
				permissions: [],
			},
			{
				name: '北俱芦州',
				path: '/world/territory/north',
				id: 27,
				parent_id: 3,
				permissions: [],
			},
		],
	},
	{
		id: 4,
		parent_id: 0,
		name: '今日股价',
		icon: 'iconfont icon-shishigujia',
		path: '/stock',
	},
	{
		id: 5,
		parent_id: 0,
		icon: 'iconfont icon-dan',
		name: '兜率宫',
		path: '/product',
	},
	{
		id: 6,
		parent_id: 0,
		name: '人员数据表',
		icon: 'iconfont icon-setting-copy',
		path: '/personnel',
		permissions: [],
	},
	{
		id: 7,
		parent_id: 0,
		name: 'share',
		icon: 'iconfont icon-shexiangji',
		path: '/share',
		children: [
			//
			{
				id: 49,
				name: '分享',
				path: '/share',
				parent_id: 7,
				permissions: [],
			},
			{
				id: 50,
				name: '通信',
				path: '/share/socket',
				parent_id: 7,
				permissions: [],
			},
		],
	},
	{
		id: 9,
		parent_id: 0,
		name: '系统',
		icon: 'iconfont icon-setting-copy',
		children: [
			{
				id: 48,
				name: '角色编辑',
				path: '/system/edit-role',
				parent_id: 9,
				permissions: [],
			},
		],
	},
	{
		id: 8,
		parent_id: 0,
		name: '设置',
		icon: 'iconfont icon-setting-copy',
		path: '/setting',
		permissions: [],
		children: [
			{
				name: '权限设置',
				path: '/setting/authority',
				id: 28,
				parent_id: 8,
				permissions: [],
			},
			{
				name: '角色权限',
				path: '/setting/role',
				id: 29,
				parent_id: 8,
				permissions: [],
			},
		],
	},
]
export default menuTree
