const permissions = [
	{ flag_key: 'PERSONNEL_C', name: '增人员', describe: '' },
	{ flag_key: 'PERSONNEL_D', name: '删人员', describe: '' },
	{ flag_key: 'PERSONNEL_U', name: '改人员', describe: '' },
	{ flag_key: 'PERSONNEL_R', name: '查人员', describe: '' },

	{ flag_key: 'PEUDUCT_C', name: '增产品', describe: '' },
	{ flag_key: 'PEUDUCT_D', name: '删产品', describe: '' },
	{ flag_key: 'PEUDUCT_U', name: '改产品', describe: '' },

	{ flag_key: 'ROLE_C', name: '增角色', describe: '' },
	{ flag_key: 'ROLE_D', name: '删角色', describe: '' },
	{ flag_key: 'ROLE_U', name: '改角色', describe: '' },
	{ flag_key: 'ROLE_R', name: '查角色', describe: '' },

	// /**地府*/
	{ name: '地狱', describe: '', flag_key: 'HELL_R' },
	// (HELL_R = 'HELL_R'),
	// 地狱十八层管理权限
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ONE_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ONE_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ONE_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ONE_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWO_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWO_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWO_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWO_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THREE_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THREE_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THREE_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THREE_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOUR_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOUR_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOUR_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOUR_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIVES_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIVES_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIVES_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIVES_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTY_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTY_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTY_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTY_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHT_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHT_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHT_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHT_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_NINE_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_NINE_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_NINE_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_NINE_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ELEVEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ELEVEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ELEVEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_ELEVEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWELVE_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWELVE_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWELVE_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_TWELVE_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THIRTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THIRTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THIRTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_THIRTEEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOURTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOURTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOURTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FOURTEEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIFTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIFTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIFTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_FIFTEEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SIXTEEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVENTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVENTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVENTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_SEVENTEEN_D' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHTEEN_C' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHTEEN_R' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHTEEN_U' },
	{ name: '地狱第  层', describe: '', flag_key: 'HELL_EIGHTEEN_D' },
	{ flag_key: '', name: 'q', describe: '' },
]
export default permissions
